### ISSUE TITLE
npm run dev does not work

### ISSUE THREAD

**Issue by ibooj** [protibimbok/django-vite-plugin#11]
Hello! 
I use pyenv. It seems that **djangoVite** does not see the python

```/home/artem/.nvm/versions/node/v18.16.0/bin/npm run dev
> frontend@0.0.0 dev
> vite

pyenv: python: command not found

The `python' command exists in these Python versions:
  3.7.8
  3.9.13
  3.9.15
  3.10.4
  3.10.8

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
```

How to fix?

**Comment by protibimbok** [comment]
Do you have a default python set up? As there are many versions available.
The plugin runs
```bash
python manage.py "arg1"
```
That assuming there is a default python available. If you have any constraints that prevents you from setting a default python version then please let me know.

**Comment by protibimbok** [comment]
Configure your `vite.config.js` file to point at the right python executable (The one you use to run `manage.py` commands).

export default defineConfig({
    plugins: [
        //Other plugins
        djangoVite({
            // Other options
            pyPath: './path/to/python' // Setting `python3` or 'py' should do the job.
        })
    ],
});

**Comment by protibimbok** [comment]
Configure your `vite.config.js` file to point at the right python executable (The one you use to run `manage.py` commands).
```javascript
export default defineConfig({
    plugins: [
        //Other plugins
        djangoVite({
            // Other options
            pyPath: './path/to/python' // `python3` or 'py' should do the job.
        })
    ],
});
```
