### ISSUE TITLE
feat: avoid assets with `vite` templatetag in `collectstatic`

### ISSUE THREAD

**Issue by scratchmex** [protibimbok/django-vite-plugin#25]
I don't know if it is worth it but at the end if the vite assets are going to be generated why include the "source code" when doing the collectstatic with django?

example

if I have `{% vite 'app/tailwind.css' %}` asset when doing collectstatic I end up with

```
static/
  app/
    tailwind.css
  assets/
    tailwind-d0be24fa.css
```

maybe even more improvement will be to integrate the vite build into `collectstatic` cmd

**Comment by protibimbok** [comment]
This plugin ignores the `collectstatic` feature of Django altogether.
You are just supposed to run:
```bash
npm run build
```
And then deploy the built files somewhere in the cloud without altering the directory structure. And then set the `BUILD_URL_PREFIX` to that directory url.
I didn't mention the collectstatic anywhere in the documentation.

> maybe even more improvement will be to integrate the vite build into `collectstatic` cmd

This is a good idea. But I think that's a bold move.
However, that will be a different topic.
