### ISSUE TITLE
What is the difference between this project and django-vite? 

### ISSUE THREAD

**Issue by asmundur-obrien** [protibimbok/django-vite-plugin#27]
Thanks for what looks like a wonderful tool. I'm new to Vite, but I am looking to integrate it with a Django webapp. And I've come across both this project, and django-vite (https://github.com/MrBin99/django-vite), of which either could potentially be what I'm looking for. But from reading through both projects it is rather unclear to me what the difference between the two is, I'm guessing there are people here that could possibly tell me the difference. I decided to post here first, since this one has had more activity in the last few days than the other.

**Comment by protibimbok** [comment]
Please refer to this:
https://forum.djangoproject.com/t/django-vite-plugin-a-minimalist-vite-helper-for-django/19842
