### ISSUE TITLE
python: can't open file '.../frontend/manage.py': No such file or direcotry

### ISSUE THREAD

**Issue by Dandada1993** [protibimbok/django-vite-plugin#3]
Attempting to use django-vite-plugin in a project where the frontend stuff including vite.config.js is in a subdirectory named 'frontend'. Manage.py is in the parent directory. When I run "npm run dev" I get the following error:

python: can't open file '/<removed for brevity>/frontend/manage.py': [Errno 2] No such file or directory

Can you modify the code so that djangoVite() can accept a parameter that indicates the path to the root of the django project for instances like mine when the vite.config.js is not in the same directory as manage.py?

**Comment by protibimbok** [comment]
Please wait for the next release. Inshallah it will be published within next two days.
Thank you
