### ISSUE TITLE
build fails with "Could not resolve entry module"  error

### ISSUE THREAD

**Issue by danielniccoli** [protibimbok/django-vite-plugin#35]
`npm run build` fails with an error.
(`npm run dev` works without issues.)

```
> site@1.0.0 build
> vite build

vite v4.4.9 building for production...
✓ 0 modules transformed.
✓ built in 10ms
Could not resolve entry module "static/src/main.js".
error during build:
RollupError: Could not resolve entry module "static/src/main.js".
    at error (file:///C:/Users/Daniel/Documents/source/project/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at ModuleLoader.loadEntryModule (file:///C:/Users/Daniel/Documents/source/project/node_modules/rollup/dist/es/shared/node-entry.js:24876:20)     
    at async Promise.all (index 0)

```

I have a special folder structure for my project.

```
.
├── site/
│   ├── settings/
│   │   └── manage.py
│   ├── app1/
│   ├── app2/
│   └── static/
│       └── src/main.js
├── node_modules/
└── vite.config.js
```

```js
//vite.config.js
import {defineConfig} from "vite"
import {djangoVitePlugin} from 'django-vite-plugin'

export default defineConfig({
    plugins: [
        djangoVitePlugin({
            input: [
                'static/src/main.js',
            ],
            root: "site",
            pyPath:".venv310/Scripts/python.exe"
        }),
    ],
})
```

```py
# settings.py
...
DJANGO_VITE_PLUGIN = {
    "STATIC_LOOKUP": False,
    "JS_ATTRS_BUILD": {"defer": True},
}
```

**Comment by danielniccoli** [comment]
After researching this for a bit, I have questions.

It looks like that when building the `input` is used to find the assets. This seems to ignore or omit the `root` prefix. Adding path from the `root` variable makes it work.

My question is: Is the `input` ignored while running the dev server and does it only play a role during building?

So in my case, the `root` variable must be `app/` so the dev server works, but the `input` should be changed to the relative path from project root and not `root`?

**Comment by protibimbok** [comment]
Yes, that is true. It's because most of the time a subdirectory of the project contains the vite assets. In that case, the root would be "..". And the root is meant to find the `manage.py` file.

**Comment by danielniccoli** [comment]
Thanks!
