### ISSUE TITLE
I am getting this error from djangoVitePlugin

### ISSUE THREAD

**Issue by eytsoft** [protibimbok/django-vite-plugin#39]
```
node:events:505rations...
      throw er; // Unhandled 'error' event
      ^

Error: spawn python ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn python',
  path: 'python',
  spawnargs: [ '../manage.py', 'django_vite_plugin', '--action', 'config' ]
}

```

**Comment by protibimbok** [comment]
Please provide me a way to recreate this error.

**Comment by 5no0p** [comment]
i face this error on ubuntu

**Comment by protibimbok** [comment]
Which command do you use to run python files? i.e. `py`, `pyton3`?

**Comment by dfrank-a** [comment]
Experiencing this same error, not sure if this is a misunderstanding over how this plugin is intended to be used. In our situation, vite and django are executing in separate containers, thus vite does not have access to python or manage.py.

**Comment by protibimbok** [comment]
The containerization does not matter. This plugin needs access of `python` and `manage.py` in vite side too,
We don't need to access the django server, just manage.py

**Comment by RobertoMaurizzi** [comment]
The call cannot find the python interpreter. On recent Ubuntu/Debian versions you need to use `python3`.
If you are in a container, add a RUN line like:
```
echo -e "interpreter:\n python: `which python||echo not found`\n python3: `which python3||echo not found`"
interpreter:
 python: not found
 python3: /usr/bin/python3
```
then check the build output to see which line gives you the path to the interpreter.

**Comment by carlkaziboni** [comment]
I face this error on macOS
> vite-react-starter@0.0.0 dev
> vite

node:events:496rations...
      throw er; // Unhandled 'error' event
      ^

Error: spawn python ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn python',
  path: 'python',
  spawnargs: [ 'manage.py', 'django_vite_plugin', '--action', 'config' ]
}

Node.js v22.11.0

**Comment by protibimbok** [comment]
@carlkaziboni 
Did you try setting `pyPath`?
```python
//vite.config.js
import { defineConfig } from 'vite'
import { djangoVitePlugin } from 'django-vite-plugin'

export default defineConfig({
    plugins: [
        djangoVitePlugin({
             input: [],
             pyPath: 'python3'
        })
    ],
});
```

**Comment by carlkaziboni** [comment]
Thank you this has fixed the issue
