### ISSUE TITLE
TypeError: Invalid value used in weak set - The `execPython()` function rejects the promise if you get a warning from Django

### ISSUE THREAD

**Issue by shtayeb** [protibimbok/django-vite-plugin#40]
## Description:
The `execPython()` in the `helper.js` file rejects the promise if you only get a Warning from Django.

## Recreate
- set `null=True` in a model field to receive a warning from django.
```py
class Donor(models.Model):
    categories= models.ManyToManyField(Category, blank=True, null=True)

```

The warning will be something like this
```shell
System check identified some issues:

WARNINGS:
myapp.Post.categories: (fields.W340) null has no effect on ManyToManyField.
```
The above message is just a warning from Django and the package should continue without interruptions.

## Suggested Solution
We can check if the error contains the string `WARNINGS:`
`src/helpers.ts`
```js
// ...
 py.on("close", () => {
      if (err && !err.includes("WARNINGS:")) {
          console.log(err);
          reject(err);
      }
      else {
          resolve(res);
      }
  });
```
### Other cases
- What if we get Warning and Error at the same time? (I have not tested this case)

**Comment by protibimbok** [comment]
Please check the pr #41. And let me know if there are any test cases left unchecked.
Another way could be disabling warnings for a specific command in Django.
Something similar to
```bash
python -W ignore manage.py ...
```
But I could not find a way to achieve this.

**Comment by shtayeb** [comment]
@protibimbok the pr looks good and it also provide better error handling.
Great job and thanks for your efforts!

**Comment by protibimbok** [comment]
Thank you for finding this bug out and reporting.
Inshallah it'll be published in the next release.
