### ISSUE TITLE
RefreshRuntime missing?

### ISSUE THREAD

**Issue by maziar-dandc** [protibimbok/django-vite-plugin#47]
Hi,

I had this error show up constantly "React refresh preamble was not loaded. Something is wrong", turns out the fix is to add this piece of code:

![image](https://github.com/protibimbok/django-vite-plugin/assets/53433222/06bbfe4b-9c73-4dcd-b349-d9a6238cbd33)
https://vitejs.dev/guide/backend-integration.html

Not sure if this is supposed to be part of this integration or not, but maybe we can add a documentation telling future users that if they want to use this with react, they will have to manually add this code in their templates.

BTW, Great work, appreciate the work you've done.

**Comment by protibimbok** [comment]
This project aims to help integrate Vite with Django backend. So, I don't think this is a good decision to include this in the documentation. Developers should be referring to the Vite's official documentation anyway.
Other than that, the default React boilerplate does not seem to add any code like this.
```bash
pnpm create vite
```

**Comment by protibimbok** [comment]
Hello @maziar-dandc,
We have decided to add the react helper.
