### ISSUE TITLE
Exception while generating build

### ISSUE THREAD

**Issue by rikardow** [protibimbok/django-vite-plugin#51]
Hi, first of all thanks for this awesome plugin

I'm trying to generate my build using Vite + Vue 3 but it's failing due to the npm plugin in the vite config

I'm adding it like `djangoVitePlugin("vue/app.ts")` since my folder structure is `<root>/vue/app.ts` and my vite config is at `<root>/vite.config.ts`, however I always get the error `TypeError: [commonjs--resolver] id.endsWith is not a function`

I tried to change the strategy, changing the path to `djangoVitePlugin(__dirname + "/vue/app.ts")` and the error changed to `django.core.exceptions.SuspiciousFileOperation: The joined path (/app/vue/app.ts) is located outside of the base path component (/usr/local/lib/python3.12/site-packages/django/contrib/admin/static)`

I'm running this on a docker container

Thanks for your help

**Comment by protibimbok** [comment]
Sorry for being so late. Please provide me your Docker config.
