### ISSUE TITLE
Setting custom host for resolveDevServerUrl

### ISSUE THREAD

**Issue by maziar-dandc** [protibimbok/django-vite-plugin#55]
Hi,

When using dockerized environments, we have to set `host: true` (aka 0.0.0.0 ipv4 / [::] ipv6) in vite config, to ensure docker container broadcasts their output, so it can be accessed by the host computer. This currently ends up making the `.hotfile` contain `http://[::]:5173` which on linux works fine, but on windows it doesn't.

I tried doing this on my own by using `config.define?._vite_custom_host` (found out `define` doesn't like strings) and `config.env?._vite_custom_host` (didn't work, couldn't debug further cause I'm noob), so would appreciate some pointers on how to go about it.

![image](https://github.com/protibimbok/django-vite-plugin/assets/53433222/541bbde3-8e7f-46a3-a24b-712c7eb85db5)

**Comment by protibimbok** [comment]
Did you try this?
```typescript
import { defineConfig } from "vite";
import { djangoVitePlugin } from "django-vite-plugin";


export default defineConfig({
    plugins: [djangoVitePlugin({
        input: [
            // entries
        ]
    })],
    server: {
        host: "0.0.0.0",
    }
});
```
