### ISSUE TITLE
Warning "The CJS build of Vite's Node API is deprecated"

### ISSUE THREAD

**Issue by tinytini12** [protibimbok/django-vite-plugin#64]
Hi! I'm getting this warning on the console when I run my project:

**The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.**

It seems like .js files are using common JS and that is going to be an error on Vite 6

**Comment by RobertoMaurizzi** [comment]
As it says on the link, 

> make sure that: 
  1 .The vite.config.js file content is using the ESM syntax.
  2 . The closest package.json file has "type": "module", or use the .mjs/.mts extension, e.g. vite.config.mjs or vite.config.mts.

**Comment by tinytini12** [comment]
> As it says on the link,
> 
> > make sure that:
> > 1 .The vite.config.js file content is using the ESM syntax.
> > 2 . The closest package.json file has "type": "module", or use the .mjs/.mts extension, e.g. vite.config.mjs or vite.config.mts.

Of course I did that and its not working. Also, set the trace to check and it found issues with the files I'm refering too above

**Comment by RobertoMaurizzi** [comment]
Ok, so which files are using CommonJS? Can you upgrade them to a version that uses modules? Or fix them, if they're your code?
In my case the only problem was the declaration in package.json (or alternatively, renaming vite.config.js to vite.config.mjs...) both worked, but our JS were already using modules from before when we used Webpack.

**Comment by tinytini12** [comment]
> Ok, so which files are using CommonJS? Can you upgrade them to a version that uses modules? Or fix them, if they're your code? In my case the only problem was the declaration in package.json (or alternatively, renaming vite.config.js to vite.config.mjs...) both worked, but our JS were already using modules from before when we used Webpack.

![Screenshot 2024-08-22 075905](https://github.com/user-attachments/assets/c02655d0-a6eb-45bd-ab72-d41ef7130e78)

config.js, helper.js, index.js

**Comment by protibimbok** [comment]
Could you please give me a way of reproducing the error?

**Comment by cpontvieux-systra** [comment]
This can be fixed using a `type: module` in your `package.json` and using the latest version (`git`, `master`) of this package.

Vite is still ok to use CommonJS for version 5 but will fail in version 6 and up.

@protibimbok can you make a npm release of the js part please? I think it will fix this issue.

**Comment by protibimbok** [comment]
Yup, I didn't publish the version because none seemed to have faced the problem.
But as it's not the case anymore, inshallah I'll publish it soon. But before publishing, I need to test if everything is working correctly.
Therefore, please give me a way to reproduce the error.

**Comment by tinytini12** [comment]
> Yup, I didn't publish the version because none seemed to have faced the problem. But as it's not the case anymore, inshallah I'll publish it soon. But before publishing, I need to test if everything is working correctly. Therefore, please give me a way to reproduce the error.

Hi! I currently have this problem with a big project that's using:

django: 5.0.7
django-vite-plugin: 3.0.0
vite: 5.4.1

Don't know if that works for you. I can't share my project

**Comment by StitiFatah** [comment]
Hi brother, first of all thanks for your package,  I however have the same problem, here is a minimal reproduction with a description in the README https://github.com/StitiFatah/cjs_deprecated_dj_vite_plugin/tree/master

**Comment by protibimbok** [comment]
Please check the latest version

**Comment by tinytini12** [comment]
Don't know why, but for me the update is causing a new error for several components ( I checked them and don't seem to have nothing strange):

`
GET http://127.0.0.1:5173/@react-refresh net::ERR_CONNECTION_REFUSED
@vitejs/plugin-react can't detect preamble. Something is wrong
`

**Comment by cpontvieux-systra** [comment]
Works great for me now, thank you !

**Comment by StitiFatah** [comment]
> Please check the latest version

The warning is gone and everything seems to work fine so far, thanks

**Comment by tinytini12** [comment]
Is working for me now too. Thank you so much!
