### ISSUE TITLE
__dirname is not defined

### ISSUE THREAD

**Issue by tinytini12** [protibimbok/django-vite-plugin#67]
Hi! With last release and using as ESM, it's showing this error:

![Screenshot 2024-09-05 142730](https://github.com/user-attachments/assets/355efca7-e668-40e4-8876-dd1bb38af21c)

How to fix: https://flaviocopes.com/fix-dirname-not-defined-es-module-scope/

**Comment by protibimbok** [comment]
Can you please give me a way to reproduce this? I know it should have happened but can't seem to encounter it.

**Comment by tinytini12** [comment]
You can use this repo: [](https://github.com/protibimbok/django-vite-plugin/issues/64#issuecomment-2315635620) updating **django-vite-plugin** package to its latest version, running npm run dev and opening http://localhost:5173/

**Comment by protibimbok** [comment]
I don't know why but I can not re create this. Please check the examples of this repo & create a pr with your problem.

**Comment by protibimbok** [comment]
You may check #69 and see if it fixes your problem.

**Comment by cmurtaugh** [comment]
I'm also having this problem; how can I install this branch in order to test?

**Comment by protibimbok** [comment]
Using pnpm
First clone this repo and cd into `vite` directory. Then run:
```bash
pnpm run build
```

You can then install it in two ways:
1. Export a tarball and install from there
```bash
pnpm pack
```
And then cd into your project and install it:
```bash
pnpm install ../path/to/tarball
```

2. Install from directory:
cd into your project and run
```
pnpm install ../path/to/cloned_repo/vite
```

**Comment by cmurtaugh** [comment]
Thanks! I was able to get the PR branch installed and it did seem to fix the problem!

**Comment by tinytini12** [comment]
Couldn't try this solution. This command throws and error in my computer `pnpm run build`

**Comment by protibimbok** [comment]
I have published the changes. Please check.

**Comment by tinytini12** [comment]
Fails for me:
`[vite] Internal server error: ENOENT: no such file or directory, open 'C:\C:\Users\my-user\my-folder\projects\my-project\node_modules\django-vite-plugin\dist\esm\info.html'`

**Comment by protibimbok** [comment]
> Couldn't try this solution. This command throws and error in my computer `pnpm run build`

Please try the same branch again. And let me know the error you are facing (if any)

**Comment by tinytini12** [comment]
> Fails for me: `[vite] Internal server error: ENOENT: no such file or directory, open 'C:\C:\Users\my-user\my-folder\projects\my-project\node_modules\django-vite-plugin\dist\esm\info.html'`

Its giving me two errors, the first one is `Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'glob'` and the second is the one above.

**Comment by protibimbok** [comment]
First pull #69 again
And then:

> Using pnpm First clone this repo and cd into `vite` directory. Then run:
> 
> ```shell
> pnpm run build
> ```
> 
> You can then install it in two ways:
> 
> 1. Export a tarball and install from there
> 
> ```shell
> pnpm pack
> ```
> 
> And then cd into your project and install it:
> 
> ```shell
> pnpm install ../path/to/tarball
> ```
> 
> 2. Install from directory:
>    cd into your project and run
> 
> ```
> pnpm install ../path/to/cloned_repo/vite
> ```

Did you follow these steps and still got no file error?

**Comment by tinytini12** [comment]
> First pull #69 again And then:
> 
> > Using pnpm First clone this repo and cd into `vite` directory. Then run:
> > ```shell
> > pnpm run build
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can then install it in two ways:
> > 
> > 1. Export a tarball and install from there
> > 
> > ```shell
> > pnpm pack
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then cd into your project and install it:
> > ```shell
> > pnpm install ../path/to/tarball
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Install from directory:
> >    cd into your project and run
> > 
> > ```
> > pnpm install ../path/to/cloned_repo/vite
> > ```
> 
> Did you follow these steps and still got no file error?

Yes, that's what I did

**Comment by protibimbok** [comment]
With type = module set in the package.json file please run the following code in terminal and send me the result.

```typescript
function getAbsolutePathFromMetaUrl(path: string): string {
    if (process.platform === 'win32' && path.startsWith('/')) {
        return path.substring(1)
    }
    return path
}
console.log(getAbsolutePathFromMetaUrl(
        typeof __dirname === 'undefined'
            ? // @ts-ignore
              path.dirname(new URL(import.meta.url).pathname)
            : __dirname,
))
```

**Comment by tinytini12** [comment]
Result

> With type = module set in the package.json file please run the following code in terminal and send me the result.
> 
> ```ts
> function getAbsolutePathFromMetaUrl(path: string): string {
>     if (process.platform === 'win32' && path.startsWith('/')) {
>         return path.substring(1)
>     }
>     return path
> }
> console.log(getAbsolutePathFromMetaUrl(
>         typeof __dirname === 'undefined'
>             ? // @ts-ignore
>               path.dirname(new URL(import.meta.url).pathname)
>             : __dirname,
> ))
> ```

Result: C:\Users\my-user\my-folder\projects\my-project

**Comment by protibimbok** [comment]
> Result: C:\Users\my-user\my-folder\projects\my-project

In that case, you are not supposed to get the error:
> Fails for me: [vite] Internal server error: ENOENT: no such file or directory, open 'C:\C:\Users\my-user\my-folder\projects\my-project\node_modules\django-vite-plugin\dist\esm\info.html'

Check: https://github.com/protibimbok/django-vite-plugin/pull/70/commits/a98c5c7ee2894a576e58900f81b3c7b6f171e2a6

It uses the exact same code to resolve the path.

Please make sure you are in the correct branch. Reference: #70

**Comment by protibimbok** [comment]
Thank you for the report. It's been updated, alhamdulillah. Please update to the latest version.

**Comment by tinytini12** [comment]
> Thank you for the report. It's been updated, alhamdulillah. Please update to the latest version.

Thank you for all the work!
