### ISSUE TITLE
How to pass  parameters to a type="module" script ?

### ISSUE THREAD

**Issue by StitiFatah** [protibimbok/django-vite-plugin#68]
Hi, 

I want to dynamically pass an ID  to some  reusable AlpineJS components that'd appear multiple times on the page to do do something like ```AlpineJS.initTree(document.querySelector(#id))``` to initialize those 

As per [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta#passing_query_parameters)  the solution is to have that in the html 

```
<script type="module">
  import "./index.mjs?someURLInfo=5";
</script> 
```

And then get the parameters  that way inside the js file

```
new URL(import.meta.url).searchParams.get("someURLInfo"); // 5
```

Is it possible to reproduce that with this plugin ? 

Maybe by getting the resolved url instead of the whole script tag  {%vite app/js/foo.js %} provides ?

Thanks in advance

**Comment by protibimbok** [comment]
Please read the documentation.

> {% vite 'your_module_path.js' type='module' %}

**Comment by StitiFatah** [comment]
> Please read the documentation.
> 
> > {% vite 'your_module_path.js' type='module' %}

I read it and  don't get what you mean. It's not passing any query parameter, just setting attributes.

**Comment by protibimbok** [comment]
Ohh, you want to modify the content of js script?
If yes, that's generated by the vite and is out of the scope of this plugin.
