### ISSUE TITLE
PluginConfig interface requires appConfig property

### ISSUE THREAD

**Issue by benjdevries** [protibimbok/django-vite-plugin#8]
Looking through the examples in this repo, when calling `djangoVite()` in the Vite config, the config object only has the `input` property, but the `PluginConfig` interface also requires the `appConfig` property. Should `appConfig` be optional on the interface like `root` and `addAliases`?

**Comment by protibimbok** [comment]
Somehow this slipped through all three test cases: `The project`, `Test Project` and `My Common Sense`
But alhamdulillah, it's fixed now.
Thank you!
